# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  #install jdk
- bash: 'wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.java.net/java/GA/jdk24.0.1/24a58e0e276943138bf3e963e6291ac2/9/GPL/openjdk-24.0.1_linux-x64_bin.tar.gz'
  displayName: 'Download Oracle JDK 24'
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 24
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: '$(build.sourcesdirectory)/openjdk-24.0.1_linux-x64_bin.tar.gz'
    jdkDestinationDirectory: '$(agent.toolsDirectory)/jdk24'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-boot:build-image -DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      # version
      $version=$pomXml.project.version
      Write-Host "##vso[task.setvariable variable=version]$version"
- task: Docker@2
  inputs:
    containerRegistry: 'qdsoftware'
    repository: 'discordbot'
    tags: |
      $(version)
      latest
    command: 'push'