server:
  port: 9020
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
management:
  server:
    port: 9020
#    endpoint:
#      shutdown:
#        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
spring:
  application:
    name: discord-bot
  servlet:
    multipart:
      file-size-threshold: 2KB
      location: /tmp
      max-file-size: 550MB
      max-request-size: 600MB
      enabled: true
  boot:
    admin:
      client:
        url: localhost:8080
        username: admin
        password: password
        instance:
          metadata:
#            user:
#              name: admin
#              password: password
  #            user.timezone: ${user.timezone}
            java.version: ${java.version}
            java.vendor: ${java.vendor}
            java.vm.name: ${java.vm.name}
            java.vm.version: ${java.vm.version}
            java.vm.vendor: ${java.vm.vendor}
            os.name: ${os.name}
            os.arch: ${os.arch}
            os.version: ${os.version}
            user.language: ${user.language}
            user.country: ${user.country}
            user.timezone: ${user.timezone}
            user.name: ${user.name}
            user.home: ${user.home}
            user.dir: ${user.dir}
            java.io.tmpdir: ${java.io.tmpdir}
            java.class.path: ${java.class.path}
            java.library.path: ${java.library.path}
            java.home: ${java.home}
            file.encoding: ${file.encoding}
            file.separator: ${file.separator}
            path.separator: ${path.separator}
            line.separator: ${line.separator}
  task:
    scheduling:
      pool:
        size: 2

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9021/eureka/

logging:
  level:
    root:
      info #debug
#    com:
#      sedmelluq:
#        discord:
#          debug
  logback:
    rollingpolicy:
      max-history: 1000000
  file:
    path: logs
    name: Discord_Bot.log