server:
  port: 9020
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
management:
  server:
    port: 9020
#    endpoint:
#      shutdown:
#        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
spring:
  application:
    name: Discord Bot
  servlet:
    multipart:
      file-size-threshold: 2KB
      location: /tmp
      max-file-size: 550MB
      max-request-size: 600MB
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:9021
        username: admin
        password: password
  task:
    scheduling:
      pool:
        size: 2

logging:
  level:
    root:
      info #debug
#    com:
#      sedmelluq:
#        discord:
#          debug
  logback:
    rollingpolicy:
      max-history: 1000000
  file:
    name: logs/Discord_Bot.log